import type { Metadata } from "next";
import "./globals.css";
import { AppFooter, AppNavbar } from "@/components/layouts";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="relative">
        <AppNavbar />
        {children}
        <AppFooter />
      </body>
    </html>
  );
}
